web:
  image: nginx:latest
  container_name: nginx
  ports:
    - "3000:80"
  volumes:
    - ./www:/www
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php


php:
  image: php:7-fpm
  container_name: php
  volumes:
    - ./www:/www
