web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./www:/www
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php


browser-sync:
  image: ustwo/browser-sync
  command: start --proxy "web:80" --files "www/*.css"
  volumes:
    - ./sandbox:/source
  ports:
    - "3000:3000"
    - "3001:3001"
  links:
    - web


php:
  image: php:7-fpm
  volumes:
    - ./www:/www
