#!/bin/bash

# integrates gulp and docker

# runs after ctrl-c
function ctrl_c() {
  echo 'Ctrl-c detected, shutting doon...'
  docker-compose down
}

# switch on argument
case "$1" in

  build)
    gulp build
    ;;

  deploy)
    echo 'deploying...'
    ;;

  down)
    docker-compose down
    ;;

  nuke)
    gulp nuke
    ;;

  up)
    docker-compose up
    ;;

  *)
    docker-compose up -d
    trap ctrl_c INT
    gulp
    ;;

esac

